{% set name = "ncar-jobqueue" %}
{% set version = "2020.12.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ncar-jobqueue-{{ version }}.tar.gz
  sha256: f62121b3d8722f76bf84b5ad43218a9faa504593c1bc94cdb948eaf0268aa301

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
    - setuptools >=30.3.0
    - setuptools_scm
  run:
    - dask-core >=2.14
    - dask-jobqueue >=0.7.1
    - jinja2
    - python >=3.6
    - pyyaml

test:
  imports:
    - ncar_jobqueue
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/NCAR/ncar-jobqueue
  summary: Utilities for expanding dask-jobqueue with appropriate settings for NCAR's clusters
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - andersy005
    - matt-long
