{% set name = "ncar-jobqueue" %}
{% set version = "2021.2.10" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ncar-jobqueue-{{ version }}.tar.gz
  sha256: dce3c0e2259de65143ac8d758ffbd8576c49b7627d5530b1e2a5925ef9e053b7

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
    - setuptools >=30.3.0
    - setuptools_scm
  run:
    - dask-core >=2.14
    - dask-jobqueue >=0.7.1
    - jinja2
    - python >=3.6
    - pyyaml

test:
  imports:
    - ncar_jobqueue
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/NCAR/ncar-jobqueue
  summary: Utilities for expanding dask-jobqueue with appropriate settings for NCAR's clusters
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - andersy005
    - matt-long
